### ISSUE TITLE
征集 Scrcpy Mask 的图标设计稿 Seeking App Icon Design Contributions

### ISSUE THREAD

**Issue by AkiChase** [AkiChase/scrcpy-mask#10]
Hello everyone,

I'm currently in the process of developing this app and seeking contributions for the design of our app icon. 
I believe that a captivating and distinctive icon is essential for making a lasting impression in today's crowded app marketplace.
I'm look forward to seeing your creative ideas and thank you in advance for your contributions!

Best regards,
AkiChase

---

总之就是征集 Scrcpy Mask 的图标设计稿，有想法的欢迎联系我

**Comment by thestmitsuki** [comment]
![image (2)](https://github.com/AkiChase/scrcpy-mask/assets/111755495/c3e6942a-fb78-4bf9-9e14-8f5738c3600a)

**Comment by AkiChase** [comment]
Thanks for your contribution! I prefer the first icon and I have used it for Scrcpy Mask v0.6.0.

Of course, if you have any better solutions for icons, feel free to keep talking!
