### ISSUE TITLE
MAC OS intel 10.14.6安装后点击没反应

### ISSUE THREAD

**Issue by wuhen8** [AkiChase/scrcpy-mask#15]
安装后点击没反应，无法启动

**Comment by AkiChase** [comment]
我没有intel的macos，无法进行测试，需要你找到错误信息。

你可以通过右键点击屏幕，观察是否弹出软件的右键菜单？如果出现则说明启动了但只有透明窗口，可以从菜单打开开发者工具查看是否有报错。

或者你下载整个项目，安装依赖后，使用`pnpm tarui run`启动项目以查看调试信息。

**Comment by wuhen8** [comment]
Service exited with abnormal code: 101

**Comment by AkiChase** [comment]
> Service exited with abnormal code: 101

错误信息有点太少了，我之后看看怎么弄一个intel的试试吧

**Comment by wuhen8** [comment]
我有虚拟机，可以提供给你测试，怎么联系

**Comment by AkiChase** [comment]
> 我有虚拟机，可以提供给你测试，怎么联系

qq: 1003019131

**Comment by AkiChase** [comment]
大概是系统版本过低，导致WebView控件兼容性问题，无法修复
