### ISSUE TITLE
网易mumu pro中是否可能通过机型伪装等行为通过模拟器检测，实现玩手游不封号？

### ISSUE THREAD

**Issue by AkiChase** [AkiChase/scrcpy-mask#19]
## 原因

显然ARM架构的电脑最适合使用模拟器，M芯片的mac属于此类。

M芯片mac目前只有网易mumu pro和Android Studio两种模拟器。但是Android Studio的模拟器优化非常差，存在很多小毛病，比如语音输入异常，进程卡死等问题。网易mumu pro优化较好，但是封号严重。

## 失败尝试

- 网易mumu pro自带的机型修改
- 安装狐狸面具后使用模块，伪装的系统字段有限

## 期望

可行的过检测方案，或者Android Studio的优化方案

**Comment by alovelydoge** [comment]
可能可行方案：
Android Studio中拉取安卓源码，然后直接在系统中硬编码相关信息，最后编译成镜像，在AVD中跑？

**Comment by AkiChase** [comment]
> 可能可行方案： Android Studio中拉取安卓源码，然后直接在系统中硬编码相关信息，最后编译成镜像，在AVD中跑？

本人是没有相关的知识储备，而且这样应该也解决不了AVD优化差的问题。

此外，有封号问题的是闭源的网易mumu pro，所以才需要修改相关信息。而Android Studio的模拟器并不会封号，一般不需要修改相关信息，只需要优化。

**Comment by Jeremyop** [comment]
有沒有人會bluestack 雷電 gameloop等過模拟器检测辦法
