### ISSUE TITLE
[BUG] Linux 无法使用

### ISSUE THREAD

**Issue by sf467** [AkiChase/scrcpy-mask#20]
**Describe the bug**
启动之后，设备页面一直在加载

**To Reproduce**
启动，点击设备页面

**Expected behavior**
正常进入设备页面，并进行设置

**Screenshots**
![image](https://github.com/AkiChase/scrcpy-mask/assets/121373973/a427037c-8e80-4e93-9045-92d546f5e55f)

**Environment  (please complete the following information):**
 - OS: Arch Linux x86_64
 - 6.9.0-x64v3-xanmod1

**Additional context**

**Comment by AkiChase** [comment]
应该是adb的问题，我没有linux的机器之前就没有测试，macOS和linux的adb是不通用的，等我更新一下吧。

**Comment by AkiChase** [comment]
应该解决了，更新即可 #22
