### ISSUE TITLE
软件获取的屏幕尺寸填入后无反应

### ISSUE THREAD

**Issue by dylanbai8** [AkiChase/scrcpy-mask#23]
小米10获取到的屏幕尺寸是 1080x2340 ，是竖屏

屏幕尺寸不管填写1080x2340，还是2340x1080都无法映射。

测试手机横屏和竖屏都没有反应。不知道是bug还是我没研究明白 :(

**Comment by AkiChase** [comment]
手机竖屏状态填入的是竖屏的分辨率，手机才会响应。横屏状态同理。

本软件获取的屏幕尺寸只能作为参考，不一定是手机真实的屏幕分辨率。你可以通过一些检测app比如安兔兔等来查看手机的分辨率。

此外，注意调节蒙版的尺寸为分辨率的一定倍数，因为在蒙版上的点击坐标，是根据蒙版尺寸和填的屏幕尺寸进行转换的。

**Comment by dylanbai8** [comment]
![image](https://github.com/AkiChase/scrcpy-mask/assets/26950227/c0ed2164-fd7a-4643-828a-2902b60ced0a)

还有个问题求解：

“将蒙版的宽度和高度设置为设备大小的一定倍数” ，可不可以是分数呀？比如三分之一。

小米10的2340x1080，我电脑上直接撑到屏幕外面了，太大了。
我设置了三分之一，780x360 ，但是好像控制不了，按键没反应

**Comment by dylanbai8** [comment]
![image](https://github.com/AkiChase/scrcpy-mask/assets/26950227/f84c90aa-1d2e-43c3-a239-3258f9df352c)

**Comment by AkiChase** [comment]
倍数可以小于1，只要长宽比例对就可以。

你可以打开开发者模式，打开指针位置显示。这样触摸操作都会在屏幕上显示，方便进行测试。

此外，映射要回到侧边栏游戏图标对应的那个蒙版界面，才会生效。你可以直接用鼠标左键点击蒙版，看看有没有显示触摸操作。

**Comment by dylanbai8** [comment]
![image](https://github.com/AkiChase/scrcpy-mask/assets/26950227/82cb0795-7fd7-4a58-a9cb-c18da96af622)

打开指针位置显示，蒙版上 没有触摸和鼠标轨迹。直接点击妙享投屏上是有的，为了排查问题 我关闭妙享和mask，使用scrcpy投屏 是有触摸轨迹的。

不知道哪里出问题了 :(

**Comment by AkiChase** [comment]
那就是分辨率不对，你可以尝试用其他app获取后输入。

我旧的oppo手机也有这个问题。在scrcpy看到过相关issue，是大致因为scrcpy-server认定的分辨率是它投屏功能中视频帧的分辨率。所以这个要填入的分辨率可能和一般方式获取到的分辨率存在差异。

**Comment by dylanbai8** [comment]
安兔兔测出来分辨率也是2340x1080 ,)

**Comment by AkiChase** [comment]
可能只有下载官方的scrcpy，然后在目录中打开命令行，执行scrcpy，查看scrcpy输出信息里的尺寸了。

![image](https://github.com/AkiChase/scrcpy-mask/assets/59353056/38280007-4051-4fd8-addf-4a0f016853f9)

这样的问题是scrcpy只有Windows系统的版本。

**Comment by AkiChase** [comment]
- https://github.com/Genymobile/scrcpy/issues/4244
- https://github.com/Genymobile/scrcpy/issues/1645

**Comment by dylanbai8** [comment]
感谢耐心指导，终于搞定了！
小米10的实际分辨率是 1080x2336

“命令行，执行scrcpy，查看scrcpy输出信息” 得到的。
再次感谢！
