### ISSUE TITLE
[Feature] 添加对 FPS 准心移动的支持

### ISSUE THREAD

**Issue by justin-himself** [AkiChase/scrcpy-mask#24]
**Is your feature request related to a problem? Please describe.**
目前 scrcpy-mask 只对王者一类的 2D 游戏做过优化，而吃鸡之类的 FPS 游戏依靠在屏幕上滑动改变视角，基本无法通过 Scrcpy Mask 现有功能游玩。同时，Scrcpy-Mask 也对鼠标左键欠缺支持，导致左键设计，右键开镜，鼠标移动改变视角的 PC FPS 逻辑无法得以实现。

**Describe the solution you'd like**
添加一个 Boss Key，按下之后隐藏鼠标指针并监听指针坐标。如果指针坐标发生改变，按下屏幕的中心点并跟随指针滑动。如果指针超出移动范围，将指针位置设回中心点。

允许绑定鼠标左键，按下 Boss Key 后鼠标左键可以开火。

参考 https://mumu.163.com/help/20210513/35047_947613.html

**Describe alternatives you've considered**
AHK 可以实现上述功能，但是 Mac 上没有好的 AHK 替代。

**Additional context**
![](https://nie.res.netease.com/r/pic/20190603/899a5ce6-09d2-4aa3-9391-85d573129f08.gif)
![](https://nie.res.netease.com/r/pic/20190603/fd06a9cf-fb39-435b-ad7f-bb1b74a211b2.gif)

**Comment by AkiChase** [comment]
v0.3.0 已支持，请导入默认方案，使用"AVD-和平精英-导入默认"方案进行尝试。

注意在游戏中设置使用固定移动、固定开火，并设置使用轮盘控制载具方向。

如果可以请给出一些反馈，比如对默认按键方案的改进等等。

**Comment by AkiChase** [comment]
这是因为要使用开火键的灵敏度，所以将鼠标重置回到准心键（同时准心键的触点也会抬起，回到准心键原始位置），因此频率高了就难免会有一点卡顿。

**Comment by AkiChase** [comment]
这个逻辑写起来有点头疼，后续看看怎么优化吧
