### ISSUE TITLE
[BUG] 蒙版尺寸大于控制设备尺寸时无法操作

### ISSUE THREAD

**Issue by L7RLBsmOOYt7Ypha** [AkiChase/scrcpy-mask#25]

**Comment by AkiChase** [comment]
应该不存在这个问题，可能是别的原因，参考 #23

**Comment by L7RLBsmOOYt7Ypha** [comment]
> 应该不存在这个问题，可能是别的原因，参考 #23 

比如说电脑分辨率为1080p，蒙版尺寸为4k，就导致整个屏幕都是蒙版区域没有设置

**Comment by AkiChase** [comment]
> > 应该不存在这个问题，可能是别的原因，参考 #23
> 
> 比如说电脑分辨率为1080p，蒙版尺寸为4k，就导致整个屏幕都是蒙版区域没有设置

蒙版尺寸只要是安卓设备分辨率的倍数（可以小于1）即可，你完全可以把蒙版设置的小一点。

**Comment by L7RLBsmOOYt7Ypha** [comment]
> > > 应该不存在这个问题，可能是别的原因，参考 #23
> > 
> > 比如说电脑分辨率为1080p，蒙版尺寸为4k，就导致整个屏幕都是蒙版区域没有设置
> 
> 蒙版尺寸只要是安卓设备分辨率的倍数（可以小于1）即可，你完全可以把蒙版设置的小一点。

现在是无法设置了,选项在屏幕外无点击

**Comment by AkiChase** [comment]
搜索一下你系统窗口最大化的快捷键，将窗口最大化即可

**Comment by L7RLBsmOOYt7Ypha** [comment]
> 搜索一下你系统窗口最大化的快捷键，将窗口最大化即可

可以了，但是建议增加个 更改尺寸后需要在n秒确认
