### ISSUE TITLE
默认安装目录是不是拼写错误

### ISSUE THREAD

**Issue by L7RLBsmOOYt7Ypha** [AkiChase/scrcpy-mask#26]
应该是Program Files
不是Program Filesl

**Comment by AkiChase** [comment]
能具体指出是哪个文件或者界面的问题吗，我暂时没找到

**Comment by L7RLBsmOOYt7Ypha** [comment]
> 能具体指出是哪个文件或者界面的问题吗，我暂时没找到

没事了，是我这边的问题
