### ISSUE TITLE
[BUG] 横屏无法使用

### ISSUE THREAD

**Issue by taotao1523** [AkiChase/scrcpy-mask#34]
**Describe the bug**
竖屏使用没有问题，但是横屏进游戏后会偏移，边缘对齐也没有用
﻿
﻿
﻿
**Screenshots**
![40B9A08630FE66BF0A3B0E528633BD5C](https://github.com/AkiChase/scrcpy-mask/assets/117962610/c2b47223-728b-41a3-9317-a84d123dcb53)
﻿
**Environment  (please complete the following information):**
- OS: windows11 
安卓12
- Version [0.4.2]
﻿
﻿
﻿

**Comment by taotao1523** [comment]
![40B9A08630FE66BF0A3B0E528633BD5C](https://github.com/AkiChase/scrcpy-mask/assets/117962610/5103f2e4-c65b-441d-b373-b6c98439598c)

**Comment by AkiChase** [comment]
安卓设备是手机还是什么？
开启安卓的自动旋转，尝试在可旋转的界面旋转安卓设备，看看scrcpy mask是否有旋转提示？

**Comment by taotao1523** [comment]
是手机，我发现了，如果是已经横屏在游戏中就会出错，要先竖屏连接上scrcpy mask再进入游戏就可以正常操控了

**Comment by AkiChase** [comment]
#38  修复了，等待下个版本发布。
