### ISSUE TITLE
[Feature] Add Support For ScreenStream

### ISSUE THREAD

**Issue by NpTIme** [AkiChase/scrcpy-mask#40]
[ScreenStream](https://github.com/dkrivoruchko/ScreenStream)
这个软件可以通过网络将屏幕投影到浏览器,在我的实测当中仅80ms的延迟(通过另一个手机的热点连接两台设备).
因为目前大多数的手机都只有usb2.0的有线传输速度,比wifi还慢,我们可以以有线方式接入操作,以无线方式投屏.
既然该软件已经使用 Tarui , 这个办法应该也能实现.
望采纳

**Comment by AkiChase** [comment]
刚刚体验了一下，如果对性能要求不高，应该是一个比较方便的解决方案。

我会尝试集成一下。
