### ISSUE TITLE
[BUG] Window error when start

### ISSUE THREAD

**Issue by NpTIme** [AkiChase/scrcpy-mask#41]
使用windows左侧边任务栏 在打开该软件时,软件窗口会卡在左上角

![image](https://github.com/AkiChase/scrcpy-mask/assets/140777598/98bce68c-9b90-4b1c-bdbe-56e308f3d7b9)

**Comment by AkiChase** [comment]
你可以用window的窗口快捷键来将窗口全屏，然后进入蒙版设置来调整蒙版位置。我在下个版本会修复这个问题。
