### ISSUE TITLE
[Feature] Auto detecting the android device with wire connection

### ISSUE THREAD

**Issue by NpTIme** [AkiChase/scrcpy-mask#42]
加入检测到usb调试的设备的自动连接.
还是这张图
![image](https://github.com/AkiChase/scrcpy-mask/assets/140777598/c4f0caba-560c-42c2-aecd-38ec18ae15f3)
我手机明明已经连接电脑了,但是还是说没有检测到

**Comment by AkiChase** [comment]
这个连接指的是使用Scrcpy-Mask连接，要在设备界面进行连接控制。
