### ISSUE TITLE
侧边按键失效

### ISSUE THREAD

**Issue by taotao1523** [AkiChase/scrcpy-mask#43]
0.4.3版本windows11 侧边按键都点不动
![image](https://github.com/AkiChase/scrcpy-mask/assets/117962610/0fd90f2e-3ec6-4bef-b0a7-fb49a9d759af)

**Comment by AkiChase** [comment]
提问时请尽可能全面而清晰地提供问题相关的信息，包括操作系统和软件版本。特别是如果有错误输出，请务必附带相关日志。

日志对定位并解决错误有所帮助。一般来说，Web 日志中就可以找到错误输出。

Web 日志：通过 Ctrl+Shift+I 或 Cmd+Opt+I 打开开发者工具，点击控制台 (console)，查看控制台内输出的信息。

**Comment by taotao1523** [comment]
web日志控制台没有任何东西
<img width="795" alt="image" src="https://github.com/AkiChase/scrcpy-mask/assets/117962610/1f1af2dd-c2d2-4e7e-bd52-a35dbf56d087">
弹出的问题也只有这些


我的意思是，我截图的按键都处于无效状态，整个软件只有“去控制”三个字能点，包括右上角最小化，全屏，关闭也点不了

<img width="962" alt="屏幕截图 2024-05-23 162258" src="https://github.com/AkiChase/scrcpy-mask/assets/117962610/39eab58f-2ed9-4df0-840d-49732db906d5">
点了去控制后跳转到页面也只有圈圈内的能操作，其他什么按键都点不动
<img width="959" alt="屏幕截图 2024-05-23 162549" src="https://github.com/AkiChase/scrcpy-mask/assets/117962610/ee2ae09d-cd81-4b55-8bf5-4dd66bc8e161">

**Comment by AkiChase** [comment]
暂时看不出来是什么问题导致的。

鼠标移动到侧边栏的按钮上是否有任何动画表现吗？

**Comment by taotao1523** [comment]
没有动画表现，就像是没有这个按键一样

**Comment by NpTIme** [comment]
我同样遇到这个bug, 症状相同。
版本最新0.4.3，系统 windows10 ltsc 2021
上一个版本没有这个bug

**Comment by AkiChase** [comment]
修复了，请等待下一版本发布
