### ISSUE TITLE
right click and hold functionality

### ISSUE THREAD

**Issue by narendersaini32** [AkiChase/scrcpy-mask#46]
**Describe the bug**
I am looking for right-click and hold functionality for a fps game but unable to found.

**To Reproduce**
1. Install any pubg mobile version.
2. For shooting left click and hold works.
3. How to add right click and hold functionality for scope?

**Expected behavior**
Need a right click and hold functionality.

**Screenshots**
![image](https://github.com/AkiChase/scrcpy-mask/assets/50134025/c3b1abbc-9a3f-4f6e-bb7f-8e6512d3e71c)

![image](https://github.com/AkiChase/scrcpy-mask/assets/50134025/2ea5cdc8-5525-4b67-b6b9-c949e3ccc0ab)

**Environment  (please complete the following information):**
 - OS: [e.g.  macOS 14.2.1]
 - Version [e.g. 1.0.0]

**Additional context**

**Comment by narendersaini32** [comment]
Right click single one time click shows browser inspect options and i need hold right click functionality.

![image](https://github.com/AkiChase/scrcpy-mask/assets/50134025/c57aa02c-4f9b-4dda-ae07-fab7b8a6e921)

**Comment by AkiChase** [comment]
1. 你可以在按键设置界面导入默认，其中的"AVD-和平精英"可以供你参考
2. 右键弹出浏览器检查选项的问题将在下个版本修复，你可以先使用 v0.4.2版本
