### ISSUE TITLE
[BUG] Key mapping migration mistake

### ISSUE THREAD

**Issue by boa-z** [AkiChase/scrcpy-mask#52]
**Describe the bug**

Some key out of screen and can't use GUI to delete after migrate.

**To Reproduce**
1. Go to 'key mapping config'
2. Click 'Migration config' and switch to new config
3. Some key out of screen and can't use GUI to delete.

**Expected behavior**
I want it to automatically change after resizing the mask.

**Screenshots**

Before

<img width="1057" alt="Screenshot 2024-05-24 at 18 24 43" src="https://github.com/AkiChase/scrcpy-mask/assets/42885162/742eb8bb-e6f2-4a04-a300-9623a2bcd5e6">

After

<img width="1317" alt="Screenshot 2024-05-24 at 18 25 52" src="https://github.com/AkiChase/scrcpy-mask/assets/42885162/6871e94a-5bc0-4ec6-95e8-f30970577cd7">
<img width="1329" alt="Screenshot 2024-05-24 at 18 25 28" src="https://github.com/AkiChase/scrcpy-mask/assets/42885162/604417c8-c0a0-404e-bde8-ad4818810c25">

**Environment  (please complete the following information):**
 - OS: [macOS 14.4.1]
 - Version [0.5.0]

**Additional context**

**Comment by AkiChase** [comment]
In your case, you don't need to migrate original config. Just export the original config, and modify the relative size in the exported json text. And then import it back.

**Comment by AkiChase** [comment]
If it works, close the issue please.
