### ISSUE TITLE
[BUG] 无法检测到通过homebrew安装的adb

### ISSUE THREAD

**Issue by juzijun233** [AkiChase/scrcpy-mask#53]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment  (please complete the following information):**
 - OS: [e.g.  macOS 14.2.1]
 - Version [e.g. 1.0.0]

**Additional context**

**Comment by AkiChase** [comment]
通过`which adb`指令获取adb路径，填入设置页面的abd路径中
