### ISSUE TITLE
[Feature] 能否弄个连点?

### ISSUE THREAD

**Issue by x67449123** [AkiChase/scrcpy-mask#58]
本来以为开火键是连点..但是用了好像没有反应,是我使用有问题还是暂时还没有这个功能..
还有使用途中延迟感有点重...是我数据线的问题吗

**Comment by AkiChase** [comment]
请描述的再具体一点，比如连点的目的是什么，在什么游戏中。

延迟一般是投屏画面可能出现延迟，控制的延迟可以忽略，你可以控制的时候看手机屏幕感受一下。
