### ISSUE TITLE
火批键位（会经常卡键，有什么解决方法吗😢）

### ISSUE THREAD

**Issue by Zzzzpgz** [AkiChase/scrcpy-mask#60]
{
  "title": "新方案-副本-副本",
  "relativeSize": {
    "h": 1080,
    "w": 2340
  },
  "list": [
    {
      "key": {
        "down": "KeyS",
        "left": "KeyA",
        "right": "KeyD",
        "up": "KeyW"
      },
      "note": "",
      "offset": 100,
      "pointerId": 1,
      "posX": 326,
      "posY": 826,
      "type": "SteeringWheel"
    },
    {
      "key": "Space",
      "note": "",
      "pointerId": 2,
      "posX": 1660,
      "posY": 963,
      "range": 30,
      "type": "DirectionalSkill"
    },
    {
      "key": "KeyJ",
      "note": "",
      "pointerId": 2,
      "posX": 1864,
      "posY": 957,
      "range": 30,
      "type": "DirectionalSkill"
    },
    {
      "key": "KeyI",
      "note": "",
      "pointerId": 2,
      "posX": 1885,
      "posY": 746,
      "range": 30,
      "type": "DirectionalSkill"
    },
    {
      "key": "KeyL",
      "note": "",
      "pointerId": 2,
      "posX": 2084,
      "posY": 645,
      "range": 30,
      "type": "DirectionalSkill"
    },
    {
      "key": "KeyK",
      "note": "",
      "pointerId": 2,
      "posX": 2071,
      "posY": 886,
      "range": 30,
      "type": "DirectionalSkill"
    },
    {
      "key": "KeyU",
      "note": "",
      "pointerId": 2,
      "posX": 1727,
      "posY": 775,
      "range": 30,
      "type": "DirectionalSkill"
    },
    {
      "key": "KeyO",
      "note": "",
      "pointerId": 2,
      "posX": 1884,
      "posY": 605,
      "range": 30,
      "type": "DirectionalSkill"
    },
    {
      "key": "KeyE",
      "note": "",
      "pointerId": 2,
      "posX": 2090,
      "posY": 444,
      "range": 30,
      "type": "DirectionalSkill"
    },
    {
      "key": "KeyR",
      "note": "",
      "pointerId": 2,
      "posX": 2090,
      "posY": 264,
      "range": 30,
      "type": "DirectionalSkill"
    }
  ]
}

**Comment by AkiChase** [comment]
每个pointerid对应一个手指，你要根据自己游戏操作的逻辑来调整，一个手指不能同时按在多个地方。

其次，虽然我觉得一般电脑或手机的性能都是足够的，但也可能和这个有关。
