### ISSUE TITLE
[BUG] Windows10系统运行scrcpy-mask不显示UI

### ISSUE THREAD

**Issue by refwww** [AkiChase/scrcpy-mask#61]
系统
> 版本	Windows 10 IoT 企业版 LTSC
版本号	21H2
安装日期	‎2024/‎1/‎18
操作系统内部版本	19044.1288
体验	Windows Feature Experience Pack 120.2212.3920.0

运行桌面上的scrcpy-mask，一个东西一闪而过，只有进程存在
请问这种怎么解决

![GIF](https://github.com/AkiChase/scrcpy-mask/assets/5498798/d53af512-7379-43eb-bb30-30162eddf8f8)

![2024-6-8_3-34-5](https://github.com/AkiChase/scrcpy-mask/assets/5498798/167aa1a7-a533-4e42-a6a2-1b5c4b9cda9e)

**Comment by AkiChase** [comment]
检查edge浏览器是否正常。这种情况一般是因为edge浏览器附带的webview2不存在而无法加载UI。

你可以试试下载安装一个webview2运行时。

如果解决了，请关闭这个issue。

**Comment by refwww** [comment]
> 检查edge浏览器是否正常。这种情况一般是因为edge浏览器附带的webview2不存在而无法加载UI。
> 
> 你可以试试下载安装一个webview2运行时。
> 
> 如果解决了，请关闭这个issue。

解决了，谢谢

第一次安装的时候没有自动安装webview2，然后卸载重装就会自动安装上webview2
