### ISSUE TITLE
[Feature] 请求在releases中添加适合windows的便携式软件包

### ISSUE THREAD

**Issue by cool-chill** [AkiChase/scrcpy-mask#63]
请求在releases中添加适合windows的便携式软件包

**Comment by AkiChase** [comment]
编译是通过Github Actions自动完成的，并没有编译为便携版的选项。

而且注意不论是否为便携版，配置文件都不是存放在安装目录下的。

你可以安装后复制一份安装目录，再把原安装的软件卸载，理论上这样和便携版的效果一样。
