### ISSUE TITLE
连接手机后不显示手机屏幕内容，辛苦大佬有时间看下哈 

### ISSUE THREAD

**Issue by z582986307** [AkiChase/scrcpy-mask#66]
小米10
usb连接手机后不显示手机屏幕内容
scrcpy就能正常显示手机上的内容
![image](https://github.com/AkiChase/scrcpy-mask/assets/74657659/471e5e66-4e3c-48b5-a5d1-3665991b2eaf)

**Comment by AkiChase** [comment]
认真看看README，然后看看我B站最新的那个视频
